---
apiVersion: v1
kind: Namespace
metadata:
  name: TMP_NAME-gcp
---
apiVersion: hive.openshift.io/v1
kind: ClusterDeployment
metadata:
  name: TMP_NAME-gcp
  namespace: TMP_NAME-gcp
  labels:
    cloud: 'GCP'
    vendor: 'OpenShift'
spec:
  baseDomain: REPLACE_BASEDOMAIN
  clusterName: TMP_NAME-gcp
  controlPlaneConfig:
    servingCertificates: {}
  installed: false
  platform:
    gcp:
      credentialsSecretRef:
        name: gcp-creds
      region: europe-west3
  provisioning:
    installConfigSecretRef:
      name: TMP_NAME-gcp-install-config
    #sshPrivateKeySecretRef:
    #  name: TMP_NAME-gcp-ssh-private-key
    imageSetRef:
       #quay.io/openshift-release-dev/ocp-release:4.5.11-x86_64
      name: imgVERSION-x86-64
  pullSecretRef:
    name: TMP_NAME-gcp-pull-secret
---
apiVersion: cluster.open-cluster-management.io/v1
kind: ManagedCluster
metadata:
  labels:
    cloud: Google
    name: TMP_NAME-gcp
    vendor: OpenShift
  name: TMP_NAME-gcp
spec:
  hubAcceptsClient: true
---
apiVersion: hive.openshift.io/v1
kind: MachinePool
metadata:
  name: TMP_NAME-gcp-worker
  namespace: TMP_NAME-gcp
spec:
  clusterDeploymentRef:
    name: TMP_NAME-gcp
  name: worker
  platform:
    gcp:
      type: n1-standard-4
  replicas: 3
---
apiVersion: agent.open-cluster-management.io/v1
kind: KlusterletAddonConfig
metadata:
  name: TMP_NAME-gcp
  namespace: TMP_NAME-gcp
spec:
  clusterName: TMP_NAME-gcp
  clusterNamespace: TMP_NAME-gcp
  clusterLabels:
    cloud: Google
    vendor: OpenShift
  applicationManager:
    enabled: true
  policyController:
    enabled: true
  searchCollector:
    enabled: true
  certPolicyController:
    enabled: true
  iamPolicyController:
    enabled: true
  version: 2.1.0
---
apiVersion: v1
kind: Secret
metadata:
  name: TMP_NAME-gcp-pull-secret
  namespace: TMP_NAME-gcp
stringData:
  .dockerconfigjson: |-
    # PASTE YOUR OPENSHIFT PULL SECRET HERE
type: kubernetes.io/dockerconfigjson
---
apiVersion: v1
kind: Secret
metadata:
  name: TMP_NAME-gcp-ssh-private-key
  namespace: TMP_NAME-gcp
stringData:
  ssh-privatekey: |-
    # PASTE YOUR SSH PRIVATE KEY HERE
type: Opaque
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: TMP_NAME-gcp-creds
  namespace: TMP_NAME-gcp
stringData:
  osServiceAccount.json: |-
    # PASTE YOUR AZURE SERVICE ACCOUNT JSON HERE
